version: "3"
services:
  keydb:
    image: bitnami/keydb:latest
    container_name: keydb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - data:/data
    restart: always

  telegrambotamd64:
    image: telegrambotamd64:1.3.1
    container_name: telegrambotamd64
    restart: always
    environment:
      - HEADER_AUTH=Bearer gtcwf6
      - TELEGRAM_TOKEN=
      - KEY_DB_ADR=keydb:6379
    depends_on:
      - keydb

volumes:
  data:
    driver: local